// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crawl.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Product struct {
	Item                 string   `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Images               string   `protobuf:"bytes,2,opt,name=images,proto3" json:"images,omitempty"`
	Stocks               string   `protobuf:"bytes,3,opt,name=stocks,proto3" json:"stocks,omitempty"`
	Harga                string   `protobuf:"bytes,4,opt,name=harga,proto3" json:"harga,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_5877e6cf3ac6969d, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *Product) GetImages() string {
	if m != nil {
		return m.Images
	}
	return ""
}

func (m *Product) GetStocks() string {
	if m != nil {
		return m.Stocks
	}
	return ""
}

func (m *Product) GetHarga() string {
	if m != nil {
		return m.Harga
	}
	return ""
}

type Products struct {
	Product              []*Product `protobuf:"bytes,1,rep,name=product,proto3" json:"product,omitempty"`
	Time                 string     `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Products) Reset()         { *m = Products{} }
func (m *Products) String() string { return proto.CompactTextString(m) }
func (*Products) ProtoMessage()    {}
func (*Products) Descriptor() ([]byte, []int) {
	return fileDescriptor_5877e6cf3ac6969d, []int{1}
}

func (m *Products) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Products.Unmarshal(m, b)
}
func (m *Products) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Products.Marshal(b, m, deterministic)
}
func (m *Products) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Products.Merge(m, src)
}
func (m *Products) XXX_Size() int {
	return xxx_messageInfo_Products.Size(m)
}
func (m *Products) XXX_DiscardUnknown() {
	xxx_messageInfo_Products.DiscardUnknown(m)
}

var xxx_messageInfo_Products proto.InternalMessageInfo

func (m *Products) GetProduct() []*Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *Products) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_5877e6cf3ac6969d, []int{2}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Product)(nil), "api.Product")
	proto.RegisterType((*Products)(nil), "api.Products")
	proto.RegisterType((*Empty)(nil), "api.Empty")
}

func init() { proto.RegisterFile("crawl.proto", fileDescriptor_5877e6cf3ac6969d) }

var fileDescriptor_5877e6cf3ac6969d = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xcd, 0xae, 0xc2, 0x20,
	0x10, 0x85, 0x6f, 0x6f, 0x7f, 0x9d, 0xea, 0x86, 0x18, 0x43, 0x5c, 0x35, 0x2c, 0xb4, 0xab, 0xc6,
	0xd4, 0x67, 0xd0, 0x75, 0xd3, 0x37, 0x40, 0x24, 0x95, 0x28, 0x81, 0x00, 0xc6, 0xf8, 0xf6, 0xa6,
	0x80, 0x89, 0xbb, 0xef, 0x7c, 0x43, 0xe6, 0x30, 0x50, 0x33, 0x43, 0x5f, 0x8f, 0x4e, 0x1b, 0xe5,
	0x14, 0x4a, 0xa9, 0x16, 0x84, 0x41, 0x39, 0x18, 0x75, 0x7d, 0x32, 0x87, 0x10, 0x64, 0xc2, 0x71,
	0x89, 0x93, 0x26, 0x69, 0x17, 0xa3, 0x67, 0xb4, 0x81, 0x42, 0x48, 0x3a, 0x71, 0x8b, 0xff, 0xbd,
	0x8d, 0x69, 0xf6, 0xd6, 0x29, 0x76, 0xb7, 0x38, 0x0d, 0x3e, 0x24, 0xb4, 0x86, 0xfc, 0x46, 0xcd,
	0x44, 0x71, 0xe6, 0x75, 0x08, 0xe4, 0x0c, 0x55, 0x2c, 0xb1, 0x68, 0x07, 0xa5, 0x0e, 0x8c, 0x93,
	0x26, 0x6d, 0xeb, 0x7e, 0xd9, 0x51, 0x2d, 0xba, 0x38, 0x1f, 0xbf, 0xc3, 0xf9, 0x37, 0x4e, 0x48,
	0x1e, 0x7b, 0x3d, 0x93, 0x12, 0xf2, 0x93, 0xd4, 0xee, 0xdd, 0x1f, 0x20, 0x1f, 0x8c, 0x92, 0x0a,
	0xed, 0xa1, 0x9a, 0xb8, 0x0b, 0x0c, 0x7e, 0x91, 0x7f, 0xb0, 0x5d, 0xfd, 0x2e, 0xb5, 0xe4, 0xef,
	0x52, 0xf8, 0x9b, 0x8f, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x87, 0x38, 0xef, 0x1a, 0x02, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PromoClient is the client API for Promo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PromoClient interface {
	GetPromo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Products, error)
}

type promoClient struct {
	cc *grpc.ClientConn
}

func NewPromoClient(cc *grpc.ClientConn) PromoClient {
	return &promoClient{cc}
}

func (c *promoClient) GetPromo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Products, error) {
	out := new(Products)
	err := c.cc.Invoke(ctx, "/api.Promo/getPromo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromoServer is the server API for Promo service.
type PromoServer interface {
	GetPromo(context.Context, *Empty) (*Products, error)
}

func RegisterPromoServer(s *grpc.Server, srv PromoServer) {
	s.RegisterService(&_Promo_serviceDesc, srv)
}

func _Promo_GetPromo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromoServer).GetPromo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Promo/GetPromo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromoServer).GetPromo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Promo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Promo",
	HandlerType: (*PromoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getPromo",
			Handler:    _Promo_GetPromo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crawl.proto",
}
