// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crawl.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Urls struct {
	Url                  []string `protobuf:"bytes,1,rep,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Urls) Reset()         { *m = Urls{} }
func (m *Urls) String() string { return proto.CompactTextString(m) }
func (*Urls) ProtoMessage()    {}
func (*Urls) Descriptor() ([]byte, []int) {
	return fileDescriptor_5877e6cf3ac6969d, []int{0}
}

func (m *Urls) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Urls.Unmarshal(m, b)
}
func (m *Urls) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Urls.Marshal(b, m, deterministic)
}
func (m *Urls) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Urls.Merge(m, src)
}
func (m *Urls) XXX_Size() int {
	return xxx_messageInfo_Urls.Size(m)
}
func (m *Urls) XXX_DiscardUnknown() {
	xxx_messageInfo_Urls.DiscardUnknown(m)
}

var xxx_messageInfo_Urls proto.InternalMessageInfo

func (m *Urls) GetUrl() []string {
	if m != nil {
		return m.Url
	}
	return nil
}

func init() {
	proto.RegisterType((*Urls)(nil), "v1.Urls")
}

func init() { proto.RegisterFile("crawl.proto", fileDescriptor_5877e6cf3ac6969d) }

var fileDescriptor_5877e6cf3ac6969d = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2e, 0x4a, 0x2c,
	0xcf, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x94, 0xe2, 0x4d, 0x4e, 0x2c,
	0x49, 0xcc, 0xc9, 0x4f, 0x87, 0x08, 0x29, 0x49, 0x70, 0xb1, 0x84, 0x16, 0xe5, 0x14, 0x0b, 0x09,
	0x70, 0x31, 0x97, 0x16, 0xe5, 0x48, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x06, 0x81, 0x98, 0x46, 0x46,
	0x5c, 0xec, 0xce, 0x20, 0xbd, 0xa9, 0x45, 0x42, 0xea, 0x5c, 0xdc, 0xee, 0xa9, 0x25, 0x01, 0x45,
	0xf9, 0x29, 0xa5, 0xc9, 0x25, 0xc5, 0x42, 0x1c, 0x7a, 0x65, 0x86, 0x7a, 0x20, 0x5d, 0x52, 0x3c,
	0x20, 0x16, 0x4c, 0x5c, 0x89, 0x21, 0x89, 0x0d, 0x6c, 0xa8, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x8d, 0x69, 0x7e, 0xa9, 0x76, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CrawlerClient is the client API for Crawler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CrawlerClient interface {
	GetProducts(ctx context.Context, in *Urls, opts ...grpc.CallOption) (*Products, error)
}

type crawlerClient struct {
	cc *grpc.ClientConn
}

func NewCrawlerClient(cc *grpc.ClientConn) CrawlerClient {
	return &crawlerClient{cc}
}

func (c *crawlerClient) GetProducts(ctx context.Context, in *Urls, opts ...grpc.CallOption) (*Products, error) {
	out := new(Products)
	err := c.cc.Invoke(ctx, "/v1.Crawler/GetProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrawlerServer is the server API for Crawler service.
type CrawlerServer interface {
	GetProducts(context.Context, *Urls) (*Products, error)
}

func RegisterCrawlerServer(s *grpc.Server, srv CrawlerServer) {
	s.RegisterService(&_Crawler_serviceDesc, srv)
}

func _Crawler_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Urls)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Crawler/GetProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServer).GetProducts(ctx, req.(*Urls))
	}
	return interceptor(ctx, in, info, handler)
}

var _Crawler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Crawler",
	HandlerType: (*CrawlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProducts",
			Handler:    _Crawler_GetProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crawl.proto",
}
