// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person struct {
	Nama                 string   `protobuf:"bytes,1,opt,name=nama,proto3" json:"nama,omitempty"`
	Alamat               string   `protobuf:"bytes,2,opt,name=alamat,proto3" json:"alamat,omitempty"`
	Telepon              string   `protobuf:"bytes,3,opt,name=telepon,proto3" json:"telepon,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetNama() string {
	if m != nil {
		return m.Nama
	}
	return ""
}

func (m *Person) GetAlamat() string {
	if m != nil {
		return m.Alamat
	}
	return ""
}

func (m *Person) GetTelepon() string {
	if m != nil {
		return m.Telepon
	}
	return ""
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Order struct {
	Vendor               Vendor   `protobuf:"varint,1,opt,name=vendor,proto3,enum=v1.Vendor" json:"vendor,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Pembeli              *Person  `protobuf:"bytes,3,opt,name=pembeli,proto3" json:"pembeli,omitempty"`
	Barang               *Product `protobuf:"bytes,4,opt,name=barang,proto3" json:"barang,omitempty"`
	Kuantitas            int32    `protobuf:"varint,5,opt,name=kuantitas,proto3" json:"kuantitas,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            int64    `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetVendor() Vendor {
	if m != nil {
		return m.Vendor
	}
	return Vendor_BLIBLI
}

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetPembeli() *Person {
	if m != nil {
		return m.Pembeli
	}
	return nil
}

func (m *Order) GetBarang() *Product {
	if m != nil {
		return m.Barang
	}
	return nil
}

func (m *Order) GetKuantitas() int32 {
	if m != nil {
		return m.Kuantitas
	}
	return 0
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type Update struct {
	Vendor               Vendor   `protobuf:"varint,1,opt,name=vendor,proto3,enum=v1.Vendor" json:"vendor,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Update) Reset()         { *m = Update{} }
func (m *Update) String() string { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()    {}
func (*Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update.Unmarshal(m, b)
}
func (m *Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update.Marshal(b, m, deterministic)
}
func (m *Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update.Merge(m, src)
}
func (m *Update) XXX_Size() int {
	return xxx_messageInfo_Update.Size(m)
}
func (m *Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Update proto.InternalMessageInfo

func (m *Update) GetVendor() Vendor {
	if m != nil {
		return m.Vendor
	}
	return Vendor_BLIBLI
}

func (m *Update) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Update) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type OrderId struct {
	Vendor               Vendor   `protobuf:"varint,1,opt,name=vendor,proto3,enum=v1.Vendor" json:"vendor,omitempty"`
	OrderId              string   `protobuf:"bytes,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderId) Reset()         { *m = OrderId{} }
func (m *OrderId) String() string { return proto.CompactTextString(m) }
func (*OrderId) ProtoMessage()    {}
func (*OrderId) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *OrderId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderId.Unmarshal(m, b)
}
func (m *OrderId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderId.Marshal(b, m, deterministic)
}
func (m *OrderId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderId.Merge(m, src)
}
func (m *OrderId) XXX_Size() int {
	return xxx_messageInfo_OrderId.Size(m)
}
func (m *OrderId) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderId.DiscardUnknown(m)
}

var xxx_messageInfo_OrderId proto.InternalMessageInfo

func (m *OrderId) GetVendor() Vendor {
	if m != nil {
		return m.Vendor
	}
	return Vendor_BLIBLI
}

func (m *OrderId) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type UserId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{4}
}

func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (m *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(m, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Orders struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Orders) Reset()         { *m = Orders{} }
func (m *Orders) String() string { return proto.CompactTextString(m) }
func (*Orders) ProtoMessage()    {}
func (*Orders) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{5}
}

func (m *Orders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Orders.Unmarshal(m, b)
}
func (m *Orders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Orders.Marshal(b, m, deterministic)
}
func (m *Orders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Orders.Merge(m, src)
}
func (m *Orders) XXX_Size() int {
	return xxx_messageInfo_Orders.Size(m)
}
func (m *Orders) XXX_DiscardUnknown() {
	xxx_messageInfo_Orders.DiscardUnknown(m)
}

var xxx_messageInfo_Orders proto.InternalMessageInfo

func (m *Orders) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "v1.Person")
	proto.RegisterType((*Order)(nil), "v1.Order")
	proto.RegisterType((*Update)(nil), "v1.Update")
	proto.RegisterType((*OrderId)(nil), "v1.OrderId")
	proto.RegisterType((*UserId)(nil), "v1.UserId")
	proto.RegisterType((*Orders)(nil), "v1.Orders")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xe1, 0x8a, 0xd3, 0x40,
	0x10, 0xc7, 0x2f, 0xed, 0x75, 0x43, 0x26, 0xe7, 0x81, 0x83, 0xc8, 0x52, 0x14, 0xea, 0xaa, 0x10,
	0x14, 0x2a, 0x57, 0x9f, 0x40, 0x14, 0x8e, 0xfb, 0xa4, 0xe4, 0x3c, 0xbf, 0xca, 0xb4, 0x3b, 0x1c,
	0xc1, 0x34, 0x1b, 0x76, 0xb7, 0x7d, 0x3a, 0xdf, 0xc4, 0x97, 0x91, 0xce, 0x26, 0xad, 0xe8, 0x17,
	0xb9, 0x6f, 0x3b, 0xff, 0xff, 0xec, 0xff, 0x37, 0x3b, 0x09, 0x94, 0xce, 0x5b, 0xf6, 0xcb, 0xde,
	0xbb, 0xe8, 0x70, 0xb2, 0xbf, 0x9a, 0x3f, 0xda, 0x50, 0xa4, 0xd6, 0xdd, 0x27, 0xc9, 0x58, 0x50,
	0x5f, 0xd8, 0x07, 0xd7, 0x21, 0xc2, 0x79, 0x47, 0x5b, 0xd2, 0xd9, 0x22, 0xab, 0x8a, 0x5a, 0xce,
	0xf8, 0x14, 0x14, 0xb5, 0xb4, 0xa5, 0xa8, 0x27, 0xa2, 0x0e, 0x15, 0x6a, 0xc8, 0x23, 0xb7, 0xdc,
	0xbb, 0x4e, 0x4f, 0xc5, 0x18, 0x4b, 0x7c, 0x02, 0x33, 0xde, 0x52, 0xd3, 0xea, 0x73, 0xd1, 0x53,
	0x61, 0x7e, 0x65, 0x30, 0xfb, 0x7c, 0x18, 0x04, 0x0d, 0xa8, 0x3d, 0x77, 0xd6, 0x79, 0xe1, 0x5c,
	0xae, 0x60, 0xb9, 0xbf, 0x5a, 0x7e, 0x13, 0xa5, 0x1e, 0x1c, 0xbc, 0x84, 0x49, 0x63, 0x07, 0xe2,
	0xa4, 0xb1, 0xf8, 0x0a, 0xf2, 0x9e, 0xb7, 0x6b, 0x6e, 0x1b, 0xa1, 0x95, 0xe9, 0x52, 0x1a, 0xbb,
	0x1e, 0x2d, 0x7c, 0x09, 0x6a, 0x4d, 0x9e, 0xba, 0x7b, 0x41, 0x97, 0xab, 0x52, 0x9a, 0xbc, 0xb3,
	0xbb, 0x4d, 0xac, 0x07, 0x0b, 0x9f, 0x41, 0xf1, 0x63, 0x47, 0x5d, 0x6c, 0x22, 0x05, 0x3d, 0x5b,
	0x64, 0xd5, 0xac, 0x3e, 0x09, 0x87, 0xe7, 0x86, 0x48, 0x71, 0x17, 0xb4, 0x4a, 0xcf, 0x4d, 0x15,
	0x3e, 0x07, 0xd8, 0x78, 0xa6, 0xc8, 0xf6, 0x3b, 0x45, 0x9d, 0x2f, 0xb2, 0x6a, 0x5a, 0x17, 0x83,
	0xf2, 0x21, 0x9a, 0xaf, 0xa0, 0xee, 0x7a, 0x4b, 0x91, 0x1f, 0xf4, 0xba, 0x13, 0x74, 0xfa, 0x27,
	0xd4, 0x5c, 0x43, 0x2e, 0x2b, 0xbb, 0xb1, 0xff, 0x15, 0xab, 0x21, 0x77, 0xa9, 0x7d, 0xc8, 0x1e,
	0x4b, 0xa3, 0x41, 0xdd, 0x05, 0xc9, 0x49, 0xe8, 0x6c, 0x44, 0x9b, 0xb7, 0xa0, 0x04, 0x11, 0xf0,
	0x05, 0x28, 0x69, 0x0f, 0x3a, 0x5b, 0x4c, 0xab, 0x72, 0x55, 0x1c, 0x08, 0xe2, 0xd5, 0x83, 0xb1,
	0xfa, 0x99, 0xc1, 0x85, 0x28, 0xb7, 0xec, 0xf7, 0xcd, 0x86, 0xb1, 0x82, 0xf2, 0xa3, 0xec, 0x20,
	0x7d, 0xd9, 0xd3, 0x95, 0xf9, 0xc5, 0xe1, 0x58, 0x73, 0xe8, 0x5d, 0x17, 0xd8, 0x9c, 0xe1, 0x6b,
	0x28, 0xae, 0x39, 0x0e, 0x28, 0x19, 0x3e, 0x0d, 0x34, 0x87, 0xe3, 0x9d, 0x60, 0xce, 0xf0, 0x1d,
	0x3c, 0x4e, 0x7b, 0xbc, 0x95, 0x0d, 0xa4, 0xd8, 0xd4, 0x2e, 0xf2, 0x3f, 0xb9, 0x6f, 0xa0, 0xfc,
	0xc4, 0x2d, 0x8f, 0x13, 0x94, 0xc7, 0xb4, 0x1b, 0xfb, 0x77, 0xef, 0x5a, 0xc9, 0xff, 0xfe, 0xfe,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x94, 0xea, 0x93, 0xd6, 0x11, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Response, error)
	GetOrders(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*Orders, error)
	UpdateStatusOrder(ctx context.Context, in *Update, opts ...grpc.CallOption) (*Response, error)
	DeleteOrder(ctx context.Context, in *OrderId, opts ...grpc.CallOption) (*Response, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/v1.OrderService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrders(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*Orders, error) {
	out := new(Orders)
	err := c.cc.Invoke(ctx, "/v1.OrderService/GetOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) UpdateStatusOrder(ctx context.Context, in *Update, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/v1.OrderService/UpdateStatusOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) DeleteOrder(ctx context.Context, in *OrderId, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/v1.OrderService/DeleteOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	CreateOrder(context.Context, *Order) (*Response, error)
	GetOrders(context.Context, *UserId) (*Orders, error)
	UpdateStatusOrder(context.Context, *Update) (*Response, error)
	DeleteOrder(context.Context, *OrderId) (*Response, error)
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.OrderService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.OrderService/GetOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrders(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_UpdateStatusOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Update)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).UpdateStatusOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.OrderService/UpdateStatusOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).UpdateStatusOrder(ctx, req.(*Update))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_DeleteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).DeleteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.OrderService/DeleteOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).DeleteOrder(ctx, req.(*OrderId))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrders",
			Handler:    _OrderService_GetOrders_Handler,
		},
		{
			MethodName: "UpdateStatusOrder",
			Handler:    _OrderService_UpdateStatusOrder_Handler,
		},
		{
			MethodName: "DeleteOrder",
			Handler:    _OrderService_DeleteOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
